In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:

df["Age"]=df["Age"].fillna(df["Age"].mean())

In [13]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [15]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [17]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [19]:
df = df.drop(columns=["Name","PassengerId","Ticket","Cabin"])

In [21]:
df

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [23]:
df['Sex'] = df['Sex'].map({'male':0,'female':1})
df

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    0  22.000000      1      0   7.2500        S
1           1       1    1  38.000000      1      0  71.2833        C
2           1       3    1  26.000000      0      0   7.9250        S
3           1       1    1  35.000000      1      0  53.1000        S
4           0       3    0  35.000000      0      0   8.0500        S
..        ...     ...  ...        ...    ...    ...      ...      ...
886         0       2    0  27.000000      0      0  13.0000        S
887         1       1    1  19.000000      0      0  30.0000        S
888         0       3    1  29.699118      1      2  23.4500        S
889         1       1    0  26.000000      0      0  30.0000        C
890         0       3    0  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [25]:
df['Embarked'] = df['Embarked'].map({'S':1,'C':2,'Q':3})
df

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0           0       3    0  22.000000      1      0   7.2500         1
1           1       1    1  38.000000      1      0  71.2833         2
2           1       3    1  26.000000      0      0   7.9250         1
3           1       1    1  35.000000      1      0  53.1000         1
4           0       3    0  35.000000      0      0   8.0500         1
..        ...     ...  ...        ...    ...    ...      ...       ...
886         0       2    0  27.000000      0      0  13.0000         1
887         1       1    1  19.000000      0      0  30.0000         1
888         0       3    1  29.699118      1      2  23.4500         1
889         1       1    0  26.000000      0      0  30.0000         2
890         0       3    0  32.000000      0      0   7.7500         3

[891 rows x 8 columns]

In [27]:
df['Age'] = df['Age'].astype(int)
df

     Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0           0       3    0   22      1      0   7.2500         1
1           1       1    1   38      1      0  71.2833         2
2           1       3    1   26      0      0   7.9250         1
3           1       1    1   35      1      0  53.1000         1
4           0       3    0   35      0      0   8.0500         1
..        ...     ...  ...  ...    ...    ...      ...       ...
886         0       2    0   27      0      0  13.0000         1
887         1       1    1   19      0      0  30.0000         1
888         0       3    1   29      1      2  23.4500         1
889         1       1    0   26      0      0  30.0000         2
890         0       3    0   32      0      0   7.7500         3

[891 rows x 8 columns]

In [29]:
df['Family'] = df['SibSp'] + df['Parch'] + 1
df

     Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked  Family
0           0       3    0   22      1      0   7.2500         1       2
1           1       1    1   38      1      0  71.2833         2       2
2           1       3    1   26      0      0   7.9250         1       1
3           1       1    1   35      1      0  53.1000         1       2
4           0       3    0   35      0      0   8.0500         1       1
..        ...     ...  ...  ...    ...    ...      ...       ...     ...
886         0       2    0   27      0      0  13.0000         1       1
887         1       1    1   19      0      0  30.0000         1       1
888         0       3    1   29      1      2  23.4500         1       4
889         1       1    0   26      0      0  30.0000         2       1
890         0       3    0   32      0      0   7.7500         3       1

[891 rows x 9 columns]

In [31]:
df = df.drop(columns=['SibSp','Parch'])
df

     Survived  Pclass  Sex  Age     Fare  Embarked  Family
0           0       3    0   22   7.2500         1       2
1           1       1    1   38  71.2833         2       2
2           1       3    1   26   7.9250         1       1
3           1       1    1   35  53.1000         1       2
4           0       3    0   35   8.0500         1       1
..        ...     ...  ...  ...      ...       ...     ...
886         0       2    0   27  13.0000         1       1
887         1       1    1   19  30.0000         1       1
888         0       3    1   29  23.4500         1       4
889         1       1    0   26  30.0000         2       1
890         0       3    0   32   7.7500         3       1

[891 rows x 7 columns]

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [34]:
X = df[['Pclass','Sex','Age','Family','Fare','Embarked']]
Y = df[['Survived']]

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=400)

In [39]:
model = RandomForestClassifier(n_estimators=100, random_state=400)

In [41]:
model.fit(X_train, Y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(random_state=400)

In [43]:
predict = model.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [47]:
accuracy = accuracy_score(Y_test, predict)
accuracy

0.8659217877094972

In [49]:
precision = precision_score(Y_test, predict)
precision

0.8194444444444444

In [51]:
recall = recall_score(Y_test, predict)
recall

0.8428571428571429

In [53]:
f1score = f1_score(Y_test, predict)
f1score

0.8309859154929577

In [57]:
def predictiontest():
    pclass = int(input("enter class = "))
    sex = int(input("enter gender = "))
    age = int(input("enter age = "))
    familysize = int(input("enter family size(currently travelling with u) = "))
    fare = float(input("enter price = "))
    embarked = int(input("enter port = "))
    
    data = pd.DataFrame(
        [[pclass, sex, age, familysize, fare, embarked]],
        columns = [
            "Pclass",
            "Sex",
            "Age",
            "Family",
            "Fare",
            "Embarked",
        ],
    )
    
    prediction = model.predict(data)[0]
    print("\nresult :- ")
    if prediction == 1:
        print("survived")
    else:
        print("died")

predictiontest()

enter class =  3
enter gender =  1
enter age =  25
enter family size(currently travelling with u) =  1
enter price =  300
enter port =  3

result :-
survived